from flask_wtf import FlaskForm
from wtforms import StringField, SelectMultipleField, HiddenField, PasswordField, SubmitField, SelectField, BooleanField
from wtforms.fields import EmailField
from wtforms.validators import DataRequired
import pandas as pd


# form for logging into the site
class LoginForm(FlaskForm):
    email = EmailField('Email')
    password = PasswordField('Password')
    submit = SubmitField('Sign In')

class KeyForm(FlaskForm):
    # api_key_choices = [("WLdDj5fvENeYbJm_3hBOhVTt9AKZLfjB9ObJZH7G6q4B7nyOJiSh8ymyLdRhb440eSUDor1KH4hVfSb8IFmXnUVp4aE6iaQZAo6u8mG6Y4sn1bz9OweGq8TOY4NGX3Yx", "API KEY 1"), ("8_8zcx7QXFgudLBc4Q4liRhDxDbVtatZi2slqVSWgz0Vm8h2KHGMfceO2U6aM39nMwOr8uWNZqMzyZnqwTQA6loO_SWM-S-QxhfwTNwZPyphds8tagBkGIj1W4JGX3Yx","API KEY 2"), ("r60CD0lw00AY2X4meETwutT_V-njGfE0lfrPiuCmqwIsMJMjqXMFHGB2lh8rOsFzi9KfKThM1KqvHstnBGQv_hHZ5MLpv7JI75Q5M8CXNfsmITVJGfWjfv7b6l_HXnYx","API KEY 3"),
    # ("86RIsBGnm-TfL7vE6g_5Wrnd0nMlbkfpLWD3ALXANbdIJyuCkWgOr06GM69lhbkzIJlS_2VqNo4hGMhPW5JESbR_hb6WWZyoz13g4M0l2S5mStf4_KAEl0vzgxM2X3Yx","API KEY 4"),]
    key = StringField(validators=[DataRequired()])
    
class SearchForm(FlaskForm):
    df = pd.read_csv('county_state.csv')
    county_maps = df.values
    SEARCH_FROM_CHOICES = [
        ('', 'Select Business Type...'),
        ('restaurants','Restaurants'),
        ('grocery_store', 'Grocery Store'),
        ('barber_shop', 'Barber Shop'),
        ('massage_salon', 'Massage Salon'),
        ('event_hall', 'Event Hall'),
        ('gym_fitness', 'Gym Fitness'),
        ('coffee_shops', 'Coffee Shops'),
        ('real_estate', 'Real Estate'),
        ('retail_shop', 'Retail Shop')
    ]
    search_from = SelectField('Search From', choices=SEARCH_FROM_CHOICES, validators=[DataRequired()])
    location_choices = [("","Choose county...")]
    for c in county_maps:
        location_choices.append((f"{c[2]}, {c[1]}#{c[0]}",f"{c[2]}, {c[1]}"))
    CATEGORY_CHOICES = [
        ('afghani', 'Afghan'),
        ('african', 'African'),
        ('senegalese', 'Senegalese'),
        ('southafrican', 'South African'),
        ('newamerican', 'American (New)'),
        ('tradamerican', 'American (Traditional)'),
        ('andalusian', 'Andalusian'),
        ('arabian', 'Arabian'),
        ('arabpizza', 'Arab Pizza'),
        ('argentine', 'Argentine'),
        ('armenian', 'Armenian'),
        ('asianfusion', 'Asian Fusion'),
        ('asturian', 'Asturian'),
        ('australian', 'Australian'),
        ('austrian', 'Austrian'),
        ('baguettes', 'Baguettes'),
        ('bangladeshi', 'Bangladeshi'),
        ('bbq', 'Barbeque'),
        ('basque', 'Basque'),
        ('bavarian', 'Bavarian'),
        ('beergarden', 'Beer Garden'),
        ('beerhall', 'Beer Hall'),
        ('beisl', 'Beisl'),
        ('belgian', 'Belgian'),
        ('flemish', 'Flemish'),
        ('bistros', 'Bistros'),
        ('blacksea', 'Black Sea'),
        ('brasseries', 'Brasseries'),
        ('brazilian', 'Brazilian'),
        ('brazilianempanadas', 'Brazilian Empanadas'),
        ('centralbrazilian', 'Central Brazilian'),
        ('northeasternbrazilian', 'Northeastern Brazilian'),
        ('northernbrazilian', 'Northern Brazilian'),
        ('rodizios', 'Rodizios'),
        ('breakfast_brunch', 'Breakfast & Brunch'),
        ('pancakes', 'Pancakes'),
        ('british', 'British'),
        ('buffets', 'Buffets'),
        ('bulgarian', 'Bulgarian'),
        ('burgers', 'Burgers'),
        ('burmese', 'Burmese'),
        ('cafes', 'Cafes'),
        ('themedcafes', 'Themed Cafes'),
        ('cafeteria', 'Cafeteria'),
        ('cajun', 'Cajun/Creole'),
        ('cambodian', 'Cambodian'),
        ('newcanadian', 'Canadian (New)'),
        ('canteen', 'Canteen'),
        ('caribbean', 'Caribbean'),
        ('dominican', 'Dominican'),
        ('haitian', 'Haitian'),
        ('puertorican', 'Puerto Rican'),
        ('trinidadian', 'Trinidadian'),
        ('catalan', 'Catalan'),
        ('cheesesteaks', 'Cheesesteaks'),
        ('chickenshop', 'Chicken Shop'),
        ('chicken_wings', 'Chicken Wings'),
        ('chilean', 'Chilean'),
        ('chinese', 'Chinese'),
        ('cantonese', 'Cantonese'),
        ('congee', 'Congee'),
        ('dimsum', 'Dim Sum'),
        ('fuzhou', 'Fuzhou'),
        ('hainan', 'Hainan'),
        ('hakka', 'Hakka'),
        ('henghwa', 'Henghwa'),
        ('hokkien', 'Hokkien'),
        ('hunan', 'Hunan'),
        ('pekinese', 'Pekinese'),
        ('shanghainese', 'Shanghainese'),
        ('szechuan', 'Szechuan'),
        ('teochew', 'Teochew'),
        ('comfortfood', 'Comfort Food'),
        ('corsican', 'Corsican'),
        ('creperies', 'Creperies'),
        ('cuban', 'Cuban'),
        ('currysausage', 'Curry Sausage'),
        ('cypriot', 'Cypriot'),
        ('czech', 'Czech'),
        ('czechslovakian', 'Czech/Slovakian'),
        ('danish', 'Danish'),
        ('delis', 'Delis'),
        ('diners', 'Diners'),
        ('dinnertheater', 'Dinner Theater'),
        ('dumplings', 'Dumplings'),
        ('eastern_european', 'Eastern European'),
        ('eritrean', 'Eritrean'),
        ('ethiopian', 'Ethiopian'),
        ('hotdogs', 'Fast Food'),
        ('filipino', 'Filipino'),
        ('fischbroetchen', 'Fischbroetchen'),
        ('fishnchips', 'Fish & Chips'),
        ('flatbread', 'Flatbread'),
        ('fondue', 'Fondue'),
        ('food_court', 'Food Court'),
        ('foodstands', 'Food Stands'),
        ('freiduria', 'Freiduria'),
        ('french', 'French'),
        ('alsatian', 'Alsatian'),
        ('auvergnat', 'Auvergnat'),
        ('berrichon', 'Berrichon'),
        ('bourguignon', 'Bourguignon'),
        ('mauritius', 'Mauritius'),
        ('nicois', 'Nicoise'),
        ('provencal', 'Provencal'),
        ('reunion', 'Reunion'),
        ('sud_ouest', 'French Southwest'),
        ('galician', 'Galician'),
        ('gamemeat', 'Game Meat'),
        ('gastropubs', 'Gastropubs'),
        ('georgian', 'Georgian'),
        ('german', 'German'),
        ('baden', 'Baden'),
        ('easterngerman', 'Eastern German'),
        ('franconian', 'Franconian'),
        ('hessian', 'Hessian'),
        ('northerngerman', 'Northern German'),
        ('palatine', 'Palatine'),
        ('rhinelandian', 'Rhinelandian'),
        ('giblets', 'Giblets'),
        ('gluten_free', 'Gluten-Free'),
        ('greek', 'Greek'),
        ('guamanian', 'Guamanian'),
        ('halal', 'Halal'),
        ('hawaiian', 'Hawaiian'),
        ('heuriger', 'Heuriger'),
        ('himalayan', 'Himalayan/Nepalese'),
        ('honduran', 'Honduran'),
        ('hkcafe', 'Hong Kong Style Cafe'),
        ('hotdog', 'Hot Dogs'),
        ('hotpot', 'Hot Pot'),
        ('hungarian', 'Hungarian'),
        ('iberian', 'Iberian'),
        ('indpak', 'Indian'),
        ('indonesian', 'Indonesian'),
        ('international', 'International'),
        ('irish', 'Irish'),
        ('island_pub', 'Island Pub'),
        ('israeli', 'Israeli'),
        ('italian', 'Italian'),
        ('abruzzese', 'Abruzzese'),
        ('altoatesine', 'Altoatesine'),
        ('apulian', 'Apulian'),
        ('calabrian', 'Calabrian'),
        ('cucinacampana', 'Cucina campana'),
        ('emilian', 'Emilian'),
        ('friulan', 'Friulan'),
        ('ligurian', 'Ligurian'),
        ('lumbard', 'Lumbard'),
        ('napoletana', 'Napoletana'),
        ('piemonte', 'Piemonte'),
        ('roman', 'Roman'),
        ('sardinian', 'Sardinian'),
        ('sicilian', 'Sicilian'),
        ('tuscan', 'Tuscan'),
        ('venetian', 'Venetian'),
        ('japanese', 'Japanese'),
        ('blowfish', 'Blowfish'),
        ('conveyorsushi', 'Conveyor Belt Sushi'),
        ('donburi', 'Donburi'),
        ('gyudon', 'Gyudon'),
        ('oyakodon', 'Oyakodon'),
        ('handrolls', 'Hand Rolls'),
        ('horumon', 'Horumon'),
        ('izakaya', 'Izakaya'),
        ('japacurry', 'Japanese Curry'),
        ('kaiseki', 'Kaiseki'),
        ('kushikatsu', 'Kushikatsu'),
        ('oden', 'Oden'),
        ('okinawan', 'Okinawan'),
        ('okonomiyaki', 'Okonomiyaki'),
        ('onigiri', 'Onigiri'),
        ('ramen', 'Ramen'),
        ('robatayaki', 'Robatayaki'),
        ('soba', 'Soba'),
        ('sukiyaki', 'Sukiyaki'),
        ('takoyaki', 'Takoyaki'),
        ('tempura', 'Tempura'),
        ('teppanyaki', 'Teppanyaki'),
        ('tonkatsu', 'Tonkatsu'),
        ('udon', 'Udon'),
        ('unagi', 'Unagi'),
        ('westernjapanese', 'Western Style Japanese Food'),
        ('yakiniku', 'Yakiniku'),
        ('yakitori', 'Yakitori'),
        ('jewish', 'Jewish'),
        ('kebab', 'Kebab'),
        ('kopitiam', 'Kopitiam'),
        ('korean', 'Korean'),
        ('kosher', 'Kosher'),
        ('kurdish', 'Kurdish'),
        ('laos', 'Laos'),
        ('laotian', 'Laotian'),
        ('latin', 'Latin American'),
        ('colombian', 'Colombian'),
        ('salvadoran', 'Salvadoran'),
        ('venezuelan', 'Venezuelan'),
        ('raw_food', 'Live/Raw Food'),
        ('lyonnais', 'Lyonnais'),
        ('malaysian', 'Malaysian'),
        ('mamak', 'Mamak'),
        ('nyonya', 'Nyonya'),
        ('meatballs', 'Meatballs'),
        ('mediterranean', 'Mediterranean'),
        ('falafel', 'Falafel'),
        ('mexican', 'Mexican'),
        ('easternmexican', 'Eastern Mexican'),
        ('jaliscan', 'Jaliscan'),
        ('northernmexican', 'Northern Mexican'),
        ('oaxacan', 'Oaxacan'),
        ('pueblan', 'Pueblan'),
        ('tacos', 'Tacos'),
        ('tamales', 'Tamales'),
        ('yucatan', 'Yucatan'),
        ('mideastern', 'Middle Eastern'),
        ('egyptian', 'Egyptian'),
        ('lebanese', 'Lebanese'),
        ('milkbars', 'Milk Bars'),
        ('modern_australian', 'Modern Australian'),
        ('modern_european', 'Modern European'),
        ('mongolian', 'Mongolian'),
        ('moroccan', 'Moroccan'),
        ('newmexican', 'New Mexican Cuisine'),
        ('newzealand', 'New Zealand'),
        ('nicaraguan', 'Nicaraguan'),
        ('nightfood', 'Night Food'),
        ('nikkei', 'Nikkei'),
        ('noodles', 'Noodles'),
        ('norcinerie', 'Norcinerie'),
        ('opensandwiches', 'Open Sandwiches'),
        ('oriental', 'Oriental'),
        ('pfcomercial', 'PF/Comercial'),
        ('pakistani', 'Pakistani'),
        ('panasian', 'Pan Asian'),
        ('eltern_cafes', 'Parent Cafes'),
        ('parma', 'Parma'),
        ('persian', 'Persian/Iranian'),
        ('peruvian', 'Peruvian'),
        ('pita', 'Pita'),
        ('pizza', 'Pizza'),
        ('polish', 'Polish'),
        ('pierogis', 'Pierogis'),
        ('polynesian', 'Polynesian'),
        ('popuprestaurants', 'Pop-Up Restaurants'),
        ('portuguese', 'Portuguese'),
        ('alentejo', 'Alentejo'),
        ('algarve', 'Algarve'),
        ('azores', 'Azores'),
        ('beira', 'Beira'),
        ('fado_houses', 'Fado Houses'),
        ('madeira', 'Madeira'),
        ('minho', 'Minho'),
        ('ribatejo', 'Ribatejo'),
        ('tras_os_montes', 'Tras-os-Montes'),
        ('potatoes', 'Potatoes'),
        ('poutineries', 'Poutineries'),
        ('pubfood', 'Pub Food'),
        ('riceshop', 'Rice'),
        ('romanian', 'Romanian'),
        ('rotisserie_chicken', 'Rotisserie Chicken'),
        ('russian', 'Russian'),
        ('salad', 'Salad'),
        ('sandwiches', 'Sandwiches'),
        ('scandinavian', 'Scandinavian'),
        ('schnitzel', 'Schnitzel'),
        ('scottish', 'Scottish'),
        ('seafood', 'Seafood'),
        ('serbocroatian', 'Serbo Croatian'),
        ('signature_cuisine', 'Signature Cuisine'),
        ('singaporean', 'Singaporean'),
        ('slovakian', 'Slovakian'),
        ('somali', 'Somali'),
        ('soulfood', 'Soul Food'),
        ('soup', 'Soup'),
        ('southern', 'Southern'),
        ('spanish', 'Spanish'),
        ('arroceria_paella', 'Arroceria / Paella'),
        ('srilankan', 'Sri Lankan'),
        ('steak', 'Steakhouses'),
        ('supperclubs', 'Supper Clubs'),
        ('sushi', 'Sushi Bars'),
        ('swabian', 'Swabian'),
        ('swedish', 'Swedish'),
        ('swissfood', 'Swiss Food'),
        ('syrian', 'Syrian'),
        ('tabernas', 'Tabernas'),
        ('taiwanese', 'Taiwanese'),
        ('tapas', 'Tapas Bars'),
        ('tapasmallplates', 'Tapas/Small Plates'),
        ('tavolacalda', 'Tavola Calda'),
        ('tex-mex', 'Tex-Mex'),
        ('thai', 'Thai'),
        ('norwegian', 'Traditional Norwegian'),
        ('traditional_swedish', 'Traditional Swedish'),
        ('trattorie', 'Trattorie'),
        ('turkish', 'Turkish'),
        ('cheekufta', 'Chee Kufta'),
        ('gozleme', 'Gozleme'),
        ('homemadefood', 'Homemade Food'),
        ('lahmacun', 'Lahmacun'),
        ('ottomancuisine', 'Ottoman Cuisine'),
        ('turkishravioli', 'Turkish Ravioli'),
        ('ukrainian', 'Ukrainian'),
        ('uzbek', 'Uzbek'),
        ('vegan', 'Vegan'),
        ('vegetarian', 'Vegetarian'),
        ('venison', 'Venison'),
        ('vietnamese', 'Vietnamese'),
        ('waffles', 'Waffles'),
        ('wok', 'Wok'),
        ('wraps', 'Wraps'),
        ('yugoslav', 'Yugoslav'),
    ]
    location = SelectField(choices=location_choices,validators=[DataRequired()])
    # latitude = StringField(validators=[DataRequired()])
    # longitude = StringField(validators=[DataRequired()])
    # radius = StringField(validators=[DataRequired()])
    category = SelectMultipleField(u'Category', choices=CATEGORY_CHOICES)

class ChainForm(FlaskForm):
    name = StringField(validators=[DataRequired()])


class UserForm(FlaskForm):
    email = StringField(validators=[DataRequired()])
    password = StringField(validators=[DataRequired()])
    is_admin = BooleanField('Admin')


class GoogleNextNForm(FlaskForm):
    n = StringField()


class GoogleSubmitJobForm(FlaskForm):
    record_id = HiddenField()
